import type { AccountBookingsResponse } from "./types";

const accountBookings: AccountBookingsResponse = {
  upcoming: [
    {
      bookingId: "12932849023",
      referenceNumber: "PETAL-4821",
      service: "Gel Manicure",
      meta: "Fri 20 Jun 2026 · 14:30 · Lena · Petal Studio, Mitte",
      status: "Confirmed",
      statusClass: "bg-[#E6F0E8] text-[#5C8F6E]",
      action: "Manage booking",
      actionHref: "/client/account/manageBooking?bookingId=12932849023",
      studioName: "Petal Studio",
      studioArea: "Mitte",
      studioAddress: "Torstraße 114 · 10119 Mitte, Berlin",
      displayDateTime: "Fri 20 Jun 2026 · 14:30",
      endTime: "16:00",
      timeRange: "14:30 - 16:00 · 1h 30m",
      technician: "Lena",
      duration: 90,
      price: 87.3,
      paymentMethod: "Visa",
      paymentLast4: "42",
      customerName: "Sofia Lindqvist",
      customerEmail: "sofia.l@email.com",
      customerPhone: "+49 170 555 0142",
      studioPhone: "+49 30 1234 5678",
      studioEmail: "hello@petalstudio.de",
      reschedulePolicy: "Free up to 24h before",
      serviceItems: [
        {
          id: "gel-manicure",
          name: "Gel Manicure",
          duration: 45,
          technician: "Lena",
          price: 45,
        },
        {
          id: "spa-pedicure",
          name: "Spa Pedicure",
          duration: 45,
          technician: "Mara",
          price: 52,
        },
      ],
      promoLabel: "Promo · PETAL10 (-10%)",
      promoDiscount: 9.7,
      totalPaid: 87.3,
    },
  ],
  history: [
    {
      bookingId: "past_1",
      referenceNumber: "PETAL-4310",
      service: "Spa Pedicure",
      meta: "22 May 2026 · Petal Studio, Mitte · €52",
      status: "Completed",
      statusClass: "text-bloom-success",
      action: "Rebook",
      actionHref: "/client/explore",
    },
    {
      bookingId: "past_2",
      referenceNumber: "PETAL-3972",
      service: "Gel Manicure",
      meta: "28 Apr 2026 · Petal Studio, Mitte · €45",
      status: "Completed",
      statusClass: "text-bloom-success",
      action: "Rebook",
      actionHref: "/client/explore",
    },
    {
      bookingId: "past_3",
      referenceNumber: "BLOOM-2288",
      service: "Classic Manicure",
      meta: "2 Apr 2026 · Bloom & Co, Prenzlauer · €32",
      status: "Completed",
      statusClass: "text-bloom-success",
      action: "Rebook",
      actionHref: "/client/explore",
    },
    {
      bookingId: "past_4",
      referenceNumber: "PETAL-1928",
      service: "Acrylic Full Set",
      meta: "14 Mar 2026 · Petal Studio, Mitte · €68",
      status: "Completed",
      statusClass: "text-bloom-success",
      action: "Rebook",
      actionHref: "/client/explore",
    },
    {
      bookingId: "past_5",
      referenceNumber: "LOTUS-1184",
      service: "Spa Pedicure",
      meta: "1 Feb 2026 · Lotus Nails, Kreuzberg · €50",
      status: "Cancelled",
      statusClass: "text-[#B0857A]",
      action: "Rebook",
      actionHref: "/client/explore",
    },
  ],
};

export async function GET() {
  return Response.json(accountBookings);
}
